version: '3.8'

services:
  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrations
    environment:
      ConnectionStrings__Postgres: "Host=db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
    depends_on:
      - db
    env_file: .env
    command: ["dotnet", "UrlShortener.Migrations.dll"]
  jaeger:
    image: jaegertracing/all-in-one:1.51
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    environment:
      COLLECTOR_OTLP_ENABLED: "true"