FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore UrlShortener.sln
RUN dotnet build UrlShortener.Migrations/UrlShortener.Migrations.csproj -c Release
RUN dotnet publish UrlShortener.Migrations/UrlShortener.Migrations.csproj -c Release -o /app

FROM mcr.microsoft.com/dotnet/runtime:8.0
WORKDIR /app
COPY --from=build /app ./
ENTRYPOINT ["dotnet", "UrlShortener.Migrations.dll"]
